### ISSUE TITLE
[QUESTION] 怎么注入logger来debug consul api request

### ISSUE THREAD

**Issue by Observer5** [hyperf/consul#3]
![image](https://user-images.githubusercontent.com/45023046/105327375-ca188e00-5c09-11eb-80ba-dfa9b05945b8.png)
![image](https://user-images.githubusercontent.com/45023046/105327409-d3a1f600-5c09-11eb-8a6c-3dfdac309f56.png)

**Comment by huangzhhui** [comment]
通过 DI 改变为你自己实现的 ConsulAgentFactory 类，你自己的 ConsulAgentFactory 类内返回的 Agent 类带上第二个参数并传入 Logger 即可
